apiVersion: v1
kind: ConfigMap
metadata:
  name: delivery-tracking-configmap
  labels:
    app: delivery-tracking
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka-0.kafka:9092"
  SERVER_PORT: "8080"
  EUREKA_CLIENT_ENABLED: "false"
