apiVersion: v1
kind: Secret
metadata:
  name:  delivery-tracking-secret
  labels:
    app: delivery-tracking
type: Opaque
stringData:
  DB_URL: jdbc:postgresql://postgres-0.postgres:5432/deliverydb
  DB_USERNAME: postgres
  DB_PASSWORD: postgres