apiVersion: v1
kind: Secret
metadata:
  name: postgres-cred
  labels:
    app: postgres
type: Opaque
stringData:                 # texto puro aqui; o K8s codifica em base64
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: deliverydb
