apiVersion: v1
kind: Pod
metadata:
  name: hellojava
  namespace: hellojava
  labels:
    app: hellojava
    tier: backend
    env: dev
  annotations:
    description: "This is a simple pod for the Hello Java application."
    release-note: "Initial release of the Hello Java application v1.0."
spec:
  containers:
  - name: hellojava
    image: hellojava:v1
    ports:
      - containerPort: 8080
